### ISSUE TITLE
Forum Module

### ISSUE THREAD

**Issue by N8boy** [IkoBB/IkoBB#28]
@ChiLLeR96 @Matzestyler 
We need for the alpha a forum module.
Who shall take a look at this?

**Tasks:**
- [ ] Define forum terms (please see also internal forum "_Forenaufbau_")
- [ ] Forum overview
- [ ] Category overview (incl. sub categories)
- [ ] Thread view
- [ ] Creating Threads
- [ ] Creating (sub)categories 
- [ ] Answering to a thread
